### PR TITLE
MacOS Compilation Support

### PR DESCRIPTION
**Pull request by YoonAddicting**
Hi there!

I noticed that the project didn't have the compilation files for MacOS out of the box, and didn't work with just using the Linux script. Because of that I created and tested the relevant files to enable compilation on MacOS. I have only tested on a Intel Mac running MacOS 14 Sonoma.

Please let me know if there is something I missed when doing the porting.

### CODE REVIEW

**Comment by bbtams** [comment]
Thank your for helping with compilation for Mac. In fact, we have this on our roadmap and need some time to test and add support for Mac (and other platforms as Android and iOS). Our developers will have a look on your pull request.

**Comment by seba-eng** [comment]
@bbtams could you maybe add a contributing guide as it is often seen in other open source projects? I think this would be beneficial for other developers who want to help and improve this project.

**Comment by bbtams** [comment]
@seba-eng Yes, this could be something for a follow-up project. Unfortunately, right now we don't have the resources to maintain a contributing guide. Our focus is on enabling support for a variety of platforms (and fixing issues of course).

**Comment by bbtams** [comment]
@YoonAddicting We added MacOS support on the develop branch. Please check if it works for you (also check the documentation). We considered your contribution but did not apply the changes to your pull request directly.

**Comment by YoonAddicting** [comment]
Thank you.  It appears to work fine for me (macOS Sonoma 14.5, x86_64).
I think it would be nice to maybe add another flag for x86_64, instead of manually editing the conan files.

**Comment by bbtams** [comment]
Yes, I will create a ticket for our internal developmen to flag --x86_64_arch. Thank you for your contribution. I will close the ticket.

**Pull request closed without merging**
